### ISSUE TITLE
dev - cleaning docker - text goes outside modal sometimes

### ISSUE THREAD

**Issue by rusher81572** [picluster/picluster#112]
Hello @TokinRing 

Can you fix this issue? The text contents sometimes goes outside of the box. Hopefully this is the last UI issue.

**Comment by rusher81572** [comment]
Still happening with prine 
<img width="874" alt="screen shot 2018-01-05 at 8 46 54 am" src="https://user-images.githubusercontent.com/5395507/34618871-0985701c-f1f5-11e7-8e71-a5f96d76b8b2.png">

And noticed it with command output

<img width="736" alt="screen shot 2018-01-05 at 8 46 22 am" src="https://user-images.githubusercontent.com/5395507/34618896-1e6d4086-f1f5-11e7-8906-1fb2e23f66e0.png">

**Comment by rusher81572** [comment]
Found another CSS issue with pulling images

<img width="753" alt="screen shot 2018-01-05 at 2 27 42 pm" src="https://user-images.githubusercontent.com/5395507/34631321-acf986e6-f224-11e7-8bd4-bdb1227455dd.png">

**Comment by TokinRing** [comment]
Fixed in PR #114
