### ISSUE TITLE
dev - missing container and node OS type images missing

### ISSUE THREAD

**Issue by TokinRing** [picluster/picluster#118]
I installed PiCluster on a fresh Arch Linux ARM install and found that font-linux is not being installed, however font-logo is. Inspecting the package.json in the webconsole component, I found that both font-linux and font-logo are defined from the same repo. Webconsole should be fixed to point to the font-logo node_module instead of font-linux.

![screenshot at 2018-01-14 13-38-18](https://user-images.githubusercontent.com/10732363/34920976-57e75f44-f930-11e7-80b4-4b6d926e4bae.png)

**Comment by rusher81572** [comment]
I think I fixed this in my recent commit. However with the new GUI changes, clicking on a container should bring up the manage container with modify and the container selected

**Comment by TokinRing** [comment]
After doing a `rm -rf web/node_modules` and then `npm i`, @rusher81572 commit fixes the font-logo issue.
