### ISSUE TITLE
Manage container does not delete as expected

### ISSUE THREAD

**Issue by TokinRing** [picluster/picluster#149]
I recently setup a mariadb container using picluster and when the container failed to start, I went to delete it from the manage container section. When the action is performed, the output is as expected however the image still shows in the container list and when running `docker container -ls` the container is still shown. 

It appears the container delete function needs looking at. Additionally each of the container management functions need to be audited and tested.

**Comment by rusher81572** [comment]
@TokinRing Delete works fine. The container list is refreshed every 5 seconds or so. So it is expected to see the old container there after a delete. If you wait a few more seconds, it should be updated. The container list page will also refresh itself every 10-15 seconds.
