### ISSUE TITLE
What is "pq" ?

### ISSUE THREAD

**Issue by al3xxx** [picluster/picluster#151]
Hello,
Could you please explain what exactly is "pq"? I couldn't find it anywhere in Arch Linux x86.

 `~> pacman -Ss pq

extra/libpqxx 6.2.5-1
    C++ client API for PostgreSQL

community/haskell-postgresql-libpq 0.9.4.2-5
    Low-level binding to libpq

~> yaourt -S pq
error: target not found: pq
`

**Comment by rusher81572** [comment]
Hello, @al3xxx.

Looks like pq is available on Ubuntu but not Arch Linux. I can not find any way that it is used. I am not using that package in production so I think it is safe to ignore that dependency. I can keep this open as a reminder to update the Github page for the next release.

**Comment by al3xxx** [comment]
Ok, that would be good - create less confusion. I use CentOS for work/server stuff and Arch for home/dev/testing, I'll try to adopt it to CentOS too if possible.
