### ISSUE TITLE
contact for inquiries 

### ISSUE THREAD

**Issue by alawik** [picluster/picluster#166]
i am wondering how to contact anyone from the team to chat about a related project

thx

**Comment by rusher81572** [comment]
Got telegram? I am verita84 or you can email me verita84@protonmail.com. I am also o. The Fediverse @verita84@rage.lol

**Comment by alawik** [comment]
@rusher81572 Do you have Discord? I can invite you to our little R&D server since we are all there outlining a game plan for this new project idea. Will be easier to chat as well.

**Comment by rusher81572** [comment]
I am rusher81572 on Discord, just setup an account

**Comment by rusher81572** [comment]
9632
