### ISSUE TITLE
Use webpack to bundle local resources

### ISSUE THREAD

**Issue by aidanharris** [picluster/picluster#33]
This will make it easier to bundle third-party dependencies with the picluster webconsole.

**Comment by TokinRing** [comment]
Reading through the basic get started page of webpack, here https://webpack.js.org/guides/getting-started/ I find that webpack will add an unneeded layer of complexity without providing any benefit.

A better use of time would be reorganizing components javascript functions into a section before the expressjs app logic on each of the three components.

I'd like to close this issue as well.
