### ISSUE TITLE
Logo concept

### ISSUE THREAD

**Issue by thorhop** [picluster/picluster#42]
Torikun mentioned the logo on ~~freenode~~ a non-FOSS compliant IRC network. I thought I could probably help kick the ball around to make a more... traditional logo. What do you think? An improvement or regression to the one on the frontpage and on the web-interface? It's still a concept, so it's not really finished in any way - it's more of a visual approximation, in the use of shapes and symbols. Personally I think we can come up with a better way of visually representing a Pi docker cluster... if you have any ideas I'll try to do another mockup and post it here :) Cheers!

![picluster-cross](https://user-images.githubusercontent.com/1967775/28652985-50e51bd6-728b-11e7-8c43-fcdf8da5700f.png)

![picluster-plus](https://user-images.githubusercontent.com/1967775/28652986-50e9145c-728b-11e7-860d-9ca6c21929a9.png)

**Comment by rusher81572** [comment]
Thank you very much, I am amazed. I like the direction. I can't wait to see the finished concept. It just needs to look good with the brown theme which I think it will.

**Comment by rusher81572** [comment]
Thanks for the wonderful logos, closing this issue
