### ISSUE TITLE
Top menu does not work after recent changes

### ISSUE THREAD

**Issue by rusher81572** [picluster/picluster#47]
Chrome reports:
```
127.0.0.1/:9 GET http://127.0.0.1:3003/node_modules/moment/min/moment.min.js 
127.0.0.1/:5 GET http://127.0.0.1:3003/node_modules/jquery/dist/jquery.min.js 
jquery-ui.js:14 Uncaught ReferenceError: jQuery is not defined
    at jquery-ui.js:14
    at jquery-ui.js:16
(anonymous) @ jquery-ui.js:14
(anonymous) @ jquery-ui.js:16
(index):9 GET http://127.0.0.1:3003/node_modules/moment/min/moment.min.js 
(index):251 Uncaught ReferenceError: $ is not defined
    at (index):251
(anonymous) @ (index):251
(index):321 Uncaught ReferenceError: $ is not defined
    at (index):321
(anonymous) @ (index):321
(index):479 Uncaught ReferenceError: $ is not defined
    at (index):479
(anonymous) @ (index):479
```

**Comment by aidanharris** [comment]
@rusher81572 Did you npm install (specifically in the web directory)? I deleted stuff from the assets directory and included them via npm instead so you'll want to npm install to pull them in. This makes dependency management easier since if we ever want to update something in the future we can just bump the version in the package.json file.

**Comment by rusher81572** [comment]
yes, I did run npm install in web dir

**Comment by aidanharris** [comment]
@rusher81572 Weird. On which page does this happen on? All of them? I'm not seeing any issues on my side so if you're still having issues you might want to wipe out the node_modules folder, re-install the dependencies with `npm install` and restart any of the services.

**Comment by rusher81572** [comment]
I wiped out the entire folder and did a git clone --recursive and same thing.

**Comment by aidanharris** [comment]
@rusher81572 What browser are you using? You shouldn't need to do a recursive clone anymore (I should update the README). Maybe try emptying your browsers cache?

**Comment by rusher81572** [comment]
Same on Chrome and Safari

**Comment by aidanharris** [comment]
@rusher81572 That's weird. I've tested on Chrome, Firefox and Safari and had no issues. 

Does this work?

```sh
ls -l web/node_modules/jquery/dist
```

If so is it loading correctly in the browser (in the network tab of the web inspector does everything look okay, e.g the status code should be 200, the response tab should look like a script containing jquery, etc).

**Comment by rusher81572** [comment]
MacBook-Pro-2:picluster rusher81572$ ls -l web/node_modules/jquery/dist
total 1760
-rw-r--r--  1 rusher81572  staff   11197 Mar 20 12:01 core.js
-rw-r--r--  1 rusher81572  staff  268039 Mar 20 12:01 jquery.js
-rw-r--r--  1 rusher81572  staff   86659 Mar 20 12:01 jquery.min.js
-rw-r--r--  1 rusher81572  staff  131666 Mar 20 12:01 jquery.min.map
-rw-r--r--  1 rusher81572  staff  215256 Mar 20 12:01 jquery.slim.js
-rw-r--r--  1 rusher81572  staff   69597 Mar 20 12:01 jquery.slim.min.js
-rw-r--r--  1 rusher81572  staff  104583 Mar 20 12:01 jquery.slim.min.map

**Comment by rusher81572** [comment]
can not see anything in network

**Comment by aidanharris** [comment]
@rusher81572 Have you restarted the webconsole since you did a `git pull`? If not you probably need to since I altered the webconsole. Other than that I have no idea why you're getting that error. I'll try to reproduce in a VM.

**Comment by rusher81572** [comment]
Worked fine using docker-compose.yml. Not sure waht is wrong

**Comment by rusher81572** [comment]
I had the same problem on my raspberry pi cluster also after pulling the code

**Comment by rusher81572** [comment]
I am not seeing it anymore, closing. ty =)

**Comment by rusher81572** [comment]
Reopening. Problem persists on my pi cluster.

Network traffic shows:
http://linux-toys.com:3003/node_modules/moment/min/moment.min.js
Cannot GET /node_modules/jquery/dist/jquery.min.js

Attaching screenshot

http://linux-toys.com:8000/test/Screen%20Shot%202017-07-27%20at%208.47.01%20PM.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20170728T034731Z&X-Amz-SignedHeaders=host&X-Amz-Expires=60000&X-Amz-Credential=EB90BT8N1SADGX1T36N4%2F20170728%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=f835eb0a71c8eb1e7bfdd98ab02dedc283483e54a4ef2a670e6c1f1701c7cd22

**Comment by rusher81572** [comment]
rm -rf node_modules
npm install
no jquery =(

**Comment by rusher81572** [comment]
I managed to get it working by removing the entire picluster directory and running npm again. Does npm just suck or something wrong with our modules?
