### ISSUE TITLE
Create non-existent containers

### ISSUE THREAD

**Issue by aidanharris** [picluster/picluster#53]
Correct my if I'm wrong but it doesn't look like we aren't creating containers properly if they exist in the config.json but aren't found in Docker. See #50 for an example of this.

We should check for non-existent images and trigger a re-build.

**Comment by rusher81572** [comment]
When you add a container, it is currently up to the user to build and create the container. I think you are saying that you want to auto build and run after adding the container. This would be a good feature for 2.1

If host failover constraints are enabled, it will automatically build and run the container on the hosts after three failed heartbeat attempts

**Comment by aidanharris** [comment]
@rusher81572 Makes sense, I only bring it up because it was causing the Travis builds to have errors. I've fixed this now though :smile:

**Comment by rusher81572** [comment]
Merged
