### ISSUE TITLE
Support `sudo`

### ISSUE THREAD

**Issue by aidanharris** [picluster/picluster#58]
Right now PiCluster has to be run as root in order to communicate with Docker. This could be seen as a security risk. It would be good if we could have a "use_sudo" setting in the config.json which would allow PiCluster to run as a non-root user and use sudo to communicate with docker.

**Comment by TokinRing** [comment]
Currently running docker as a non-root user requires adding said non-root user to a privileged docker group, which is a root equivalent group. The details of which are discussed here https://github.com/moby/moby/issues/9976

From the looks of it, this isn't high on the docker teams priority list. So wrapping docker in sudo does nothing for security and adds an unnecessary extra setup step. If docker does get around to improving their privilege separation, I'll be the first to jump on board.

Until then, I'd like to close this issue.
