### ISSUE TITLE
DNS Updating or Webhooks on Container Host Change?

### ISSUE THREAD

**Issue by benyanke** [picluster/picluster#90]
_(New to the project, but very hyped about it after hearing on a recent Jupiter Broadcasting episode)_

Is there any built-in methods for updating DNS records or other configs when containers change hosts? I'd like to consider using this with production websites, once I'm comfortable...but would need to update DNS entries for each container, to ensure they can float between VPS instances smoothly.

**Comment by rusher81572** [comment]
Hello and thank you for taking interest in PiCluster. I want to make sure that it can help you be successful in your task. There is no built-in way to manage DNS. PiCluster does not set specific routes for applications like Swarm/Kubernetes/or traditional PaaS does. Right now, it is best to use a Load Balancer like Nginx in front of PICluster. At home, I use Nginx and exposed the same port on every host so I can migrate containers to any host. 

One thing that may help or interest you is that PiCluster can manage a Virtual IP between two hosts. For example, if node1 goes down, the public virtual IP can failover to node2 or vice versa. That way you will not have to manage DNS for PiCluster access. If your Load balancer points to one of these two hosts, then you can accomplish what you want. 

If you have any questions, please let me know.

**Comment by benyanke** [comment]
I heard you discuss the virtual IPs, but how would that work on a VPS, where the networking is significantly more locked-down? For example, digital ocean? They have a floating-ip function, but could you tie into that?

**Comment by rusher81572** [comment]
I have never tested it on a VPS yet =( . However, If you can bring up the floating virtual IP using the "ip" command on either host, then PiCluster will be able to handle it because it would be doing it the same way.

**Comment by rusher81572** [comment]
One thing to note that in the PiCluster code, it will create and delete VIP's using the /32 CIDR length.  If that will not work for you, I can change it or you can change it in agent.js on lines 153-154. /32 seemed to be the default on my network with the IP command.

**Comment by benyanke** [comment]
you can't do it with the IP call, but you can do it with a Digital Ocean API call. If I go this route, perhaps I could add some API functionality for DO to handle this!

**Comment by rusher81572** [comment]
That would be a great addition! Lines 153-154 of agent.js can be customizable via an override from config.json or directly in the code with the curl command or API calls for DO. The latter would be the quicker solution in the short term.

**Comment by benyanke** [comment]
Opening the idea as it's own ticket at #91, so I (or someone else) can implement later more cleanly.
