### ISSUE TITLE
CSS issues in dev

### ISSUE THREAD

**Issue by rusher81572** [picluster/picluster#94]
[Archive.zip](https://github.com/picluster/picluster/files/1354582/Archive.zip)

1. Sub-menu items look smashed together.
2. Node display window cut off on bottom
3. View function is no longer a modal
4. Functions awaiting data retrieval window is only the title, no body.

**Comment by TokinRing** [comment]
<img width="273" alt="screen shot 2017-10-03 at 9 45 32 pm" src="https://user-images.githubusercontent.com/10732363/31183841-9cf17f1a-a8dc-11e7-8079-26f1f4faae87.png">
<img width="952" alt="screen shot 2017-10-03 at 9 45 42 pm" src="https://user-images.githubusercontent.com/10732363/31183843-9cfddc7e-a8dc-11e7-8ede-1cc17dfd0f18.png">
<img width="901" alt="screen shot 2017-10-03 at 9 45 51 pm" src="https://user-images.githubusercontent.com/10732363/31183842-9cf86442-a8dc-11e7-9259-751397b415eb.png">
<img width="1042" alt="screen shot 2017-10-03 at 9 46 01 pm" src="https://user-images.githubusercontent.com/10732363/31183844-9cfe52c6-a8dc-11e7-9643-22fb5a09b0cc.png">

**Comment by rusher81572** [comment]
No more textbox for failover constraints?
<img width="875" alt="screen shot 2017-10-04 at 2 42 11 pm" src="https://user-images.githubusercontent.com/5395507/31201088-468fbaca-a912-11e7-8f5d-b62740baf61e.png">

**Comment by rusher81572** [comment]
The log options
<img width="869" alt="screen shot 2017-10-04 at 2 43 46 pm" src="https://user-images.githubusercontent.com/5395507/31201155-7c146c40-a912-11e7-821a-04ea2faba671.png">
 are missing checkbox labels

**Comment by rusher81572** [comment]
Upload container files no longer has a button around

<img width="875" alt="screen shot 2017-10-04 at 2 45 16 pm" src="https://user-images.githubusercontent.com/5395507/31201209-b4491926-a912-11e7-8d79-90f25033f210.png">

**Comment by rusher81572** [comment]
Running Containers modal window is cut off

<img width="1107" alt="screen shot 2017-10-04 at 2 48 50 pm" src="https://user-images.githubusercontent.com/5395507/31201345-310edee6-a913-11e7-9b3a-5a4a543a730c.png">

**Comment by rusher81572** [comment]
Major CSS issues
<img width="779" alt="screen shot 2017-10-06 at 12 24 17 pm" src="https://user-images.githubusercontent.com/5395507/31294859-5ccf39fc-aa91-11e7-97b1-39d614402966.png">
<img width="774" alt="screen shot 2017-10-06 at 12 23 54 pm" src="https://user-images.githubusercontent.com/5395507/31294862-5cd35eba-aa91-11e7-8aed-268c60266d5d.png">
<img width="767" alt="screen shot 2017-10-06 at 12 23 47 pm" src="https://user-images.githubusercontent.com/5395507/31294858-5cce8c00-aa91-11e7-9a60-7f80040762a3.png">
<img width="771" alt="screen shot 2017-10-06 at 12 23 40 pm" src="https://user-images.githubusercontent.com/5395507/31294861-5cd339e4-aa91-11e7-9906-a9c4a8999720.png">
<img width="898" alt="screen shot 2017-10-06 at 12 23 29 pm" src="https://user-images.githubusercontent.com/5395507/31294863-5ce142dc-aa91-11e7-95fc-5bb30a95cf7f.png">
<img width="876" alt="screen shot 2017-10-06 at 12 23 12 pm" src="https://user-images.githubusercontent.com/5395507/31294860-5ccfa02c-aa91-11e7-928c-0d08699e427a.png">
<img width="846" alt="screen shot 2017-10-06 at 12 23 03 pm" src="https://user-images.githubusercontent.com/5395507/31294865-5ce67054-aa91-11e7-812f-dde168529a41.png">
<img width="877" alt="screen shot 2017-10-06 at 12 22 56 pm" src="https://user-images.githubusercontent.com/5395507/31294864-5ce559e4-aa91-11e7-9907-fcb93fdb58ae.png">
<img width="769" alt="screen shot 2017-10-06 at 12 22 48 pm" src="https://user-images.githubusercontent.com/5395507/31294866-5ce82d9a-aa91-11e7-802f-ec2a9e396e48.png">
<img width="905" alt="screen shot 2017-10-06 at 12 22 39 pm" src="https://user-images.githubusercontent.com/5395507/31294867-5ce90ac6-aa91-11e7-8697-88771bd03cfd.png">
<img width="856" alt="screen shot 2017-10-06 at 12 21 55 pm" src="https://user-images.githubusercontent.com/5395507/31294868-5cfc244e-aa91-11e7-996d-6a4ee15d8e92.png">
<img width="547" alt="screen shot 2017-10-06 at 12 21 10 pm" src="https://user-images.githubusercontent.com/5395507/31294869-5cfe1dbc-aa91-11e7-9a47-3a883ff217b4.png">

**Comment by rusher81572** [comment]
<img width="769" alt="screen shot 2017-10-06 at 12 27 50 pm" src="https://user-images.githubusercontent.com/5395507/31295029-dfbcf53e-aa91-11e7-87b5-b5c321569d6f.png">

**Comment by rusher81572** [comment]
Some things are better after the latest PR, many are bad like button and window sizing.

<img width="865" alt="screen shot 2017-10-08 at 5 18 26 pm" src="https://user-images.githubusercontent.com/5395507/31322466-d6811df8-ac4c-11e7-8310-14dbfcb57915.png">
<img width="856" alt="screen shot 2017-10-08 at 5 18 15 pm" src="https://user-images.githubusercontent.com/5395507/31322467-d6821fe6-ac4c-11e7-8267-b1007e134594.png">
<img width="870" alt="screen shot 2017-10-08 at 5 18 00 pm" src="https://user-images.githubusercontent.com/5395507/31322471-d683add4-ac4c-11e7-9fbc-f28a49c37a8d.png">
<img width="873" alt="screen shot 2017-10-08 at 5 17 41 pm" src="https://user-images.githubusercontent.com/5395507/31322468-d68225b8-ac4c-11e7-9035-5d11839dffe6.png">
<img width="885" alt="screen shot 2017-10-08 at 5 17 26 pm" src="https://user-images.githubusercontent.com/5395507/31322469-d68291a6-ac4c-11e7-941c-88494486b497.png">
<img width="985" alt="screen shot 2017-10-08 at 5 17 00 pm" src="https://user-images.githubusercontent.com/5395507/31322470-d682b780-ac4c-11e7-9a06-0a91440d141f.png">
<img width="984" alt="screen shot 2017-10-08 at 5 16 38 pm" src="https://user-images.githubusercontent.com/5395507/31322472-d6967860-ac4c-11e7-8669-57b2ceac6582.png">
<img width="691" alt="screen shot 2017-10-08 at 5 15 55 pm" src="https://user-images.githubusercontent.com/5395507/31322473-d69ca104-ac4c-11e7-9945-195675e8c2a8.png">

**Comment by rusher81572** [comment]
New CSS issues.
<img width="917" alt="screen shot 2017-10-09 at 1 26 40 pm" src="https://user-images.githubusercontent.com/5395507/31357203-9dd46d1c-acf5-11e7-95a9-453d9bdbe161.png">
<img width="933" alt="screen shot 2017-10-09 at 1 26 22 pm" src="https://user-images.githubusercontent.com/5395507/31357202-9dd3562a-acf5-11e7-9ef5-f1f33b5f7d58.png">
<img width="619" alt="screen shot 2017-10-09 at 1 26 11 pm" src="https://user-images.githubusercontent.com/5395507/31357204-9dd4a5fc-acf5-11e7-9d91-41c2e2389ef9.png">
<img width="1160" alt="screen shot 2017-10-09 at 1 25 47 pm" src="https://user-images.githubusercontent.com/5395507/31357207-9dd729ee-acf5-11e7-86ec-e7b39b2341da.png">
<img width="1192" alt="screen shot 2017-10-09 at 1 25 41 pm" src="https://user-images.githubusercontent.com/5395507/31357205-9dd4971a-acf5-11e7-9b6c-1ada33a3c181.png">
<img width="1172" alt="screen shot 2017-10-09 at 1 25 24 pm" src="https://user-images.githubusercontent.com/5395507/31357206-9dd5e91c-acf5-11e7-85d1-7a40d915fced.png">
<img width="1176" alt="screen shot 2017-10-09 at 1 25 14 pm" src="https://user-images.githubusercontent.com/5395507/31357209-9dfd3404-acf5-11e7-8ef8-de47327acb2a.png">
<img width="1159" alt="screen shot 2017-10-09 at 1 25 08 pm" src="https://user-images.githubusercontent.com/5395507/31357208-9debacac-acf5-11e7-8c2f-20fc979e1fa9.png">

**Comment by rusher81572** [comment]
New CSS issues with the latest dev branch 

<img width="733" alt="screen shot 2017-11-08 at 9 43 45 am" src="https://user-images.githubusercontent.com/5395507/32564579-8c244d18-c469-11e7-8be2-ddc52a1f8230.png">
<img width="724" alt="screen shot 2017-11-08 at 9 43 52 am" src="https://user-images.githubusercontent.com/5395507/32564580-8c48150e-c469-11e7-84c0-43eadaf66ea5.png">
<img width="730" alt="screen shot 2017-11-08 at 9 44 10 am" src="https://user-images.githubusercontent.com/5395507/32564581-8c670d88-c469-11e7-9cdb-e2f118fedbf5.png">
<img width="708" alt="screen shot 2017-11-08 at 9 44 18 am" src="https://user-images.githubusercontent.com/5395507/32564582-8c8441f0-c469-11e7-99fe-275dc560e067.png">
<img width="724" alt="screen shot 2017-11-08 at 9 44 47 am" src="https://user-images.githubusercontent.com/5395507/32564583-8cb4567e-c469-11e7-8d16-71d8757c1de7.png">
<img width="961" alt="screen shot 2017-11-08 at 9 42 55 am" src="https://user-images.githubusercontent.com/5395507/32564586-911d24f2-c469-11e7-9949-4b12db412015.png">
<img width="961" alt="screen shot 2017-11-08 at 9 43 05 am" src="https://user-images.githubusercontent.com/5395507/32564587-913b694e-c469-11e7-9e0d-c37caf425720.png">
<img width="818" alt="screen shot 2017-11-08 at 9 43 21 am" src="https://user-images.githubusercontent.com/5395507/32564588-916b86ec-c469-11e7-943e-5e628c038776.png">
<img width="958" alt="screen shot 2017-11-08 at 9 43 33 am" src="https://user-images.githubusercontent.com/5395507/32564589-918e9a74-c469-11e7-92e8-e7992e090f58.png">

**Comment by rusher81572** [comment]
<img width="688" alt="screen shot 2017-11-17 at 10 01 52 am" src="https://user-images.githubusercontent.com/5395507/32961699-6b9fe342-cb7e-11e7-8876-1f271ff11d8a.png">

**Comment by TokinRing** [comment]
I can see the UI errors on a few of the images, such as the terminal and cleaning views. However I am not fully understanding the problems on the images, log, or function views. Would you please elaborate underneath each image a synopsis of the UI problem experienced?
